substitutions:
  name: m5stack-atom-echo
  friendly_name: M5Stack Atom Echo

esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  min_version: 2025.2.0

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0

logger:
api:

ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ap:

captive_portal:


i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO5
    

speaker:
  - platform: i2s_audio
    id: echo_speaker
    #i2s_dout_pin: GPIO22
    i2s_dout_pin: GPIO26
    dac_type: external
    #bits_per_sample: 32bit
    #channel: right
    #buffer_duration: 60ms
    mode: mono

media_player:
  - platform: speaker
    name: None
    id: echo_media_player
    announcement_pipeline:
      speaker: echo_speaker
      format: MP3
    codec_support_enabled: false
    buffer_size: 6000
